#!/usr/bin/env python3
"""Generate CHANGELOG.md from tags and commits.

There were no versions and no changelog, so `chewbacca update` pulled an
unknown number of unknown changes and the only release documentation was the
commit log, which is excellent and which nobody reads.

  python3 tools/changelog.py            rewrite CHANGELOG.md
  python3 tools/changelog.py --check    exit 1 if it is behind HEAD
"""

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "CHANGELOG.md"

# Conventional-ish prefixes to human sections. Anything unmatched goes to Other,
# which is a signal to write a better commit message, not to hide the commit.
SECTIONS = [
    ("Added", ("feat", "add")),
    ("Fixed", ("fix",)),
    ("Changed", ("refactor", "perf", "chore", "counts", "people", "plynn")),
    ("Documentation", ("docs",)),
]


def git(*args):
    return subprocess.run(["git", "-C", str(REPO), *args],
                          capture_output=True, text=True).stdout.strip()


def tags():
    out = git("tag", "--sort=-creatordate")
    return [t for t in out.split("\n") if t]


def commits(rng):
    out = git("log", "--no-merges", "--pretty=%s", rng)
    return [c for c in out.split("\n") if c]


def classify(subjects):
    buckets = {name: [] for name, _ in SECTIONS}
    buckets["Other"] = []
    for s in subjects:
        prefix = s.split(":", 1)[0].strip().lower()
        for name, keys in SECTIONS:
            if prefix in keys:
                buckets[name].append(s.split(":", 1)[1].strip() if ":" in s else s)
                break
        else:
            buckets["Other"].append(s)
    return buckets


def render_release(title, date, subjects):
    lines = [f"## {title}" + (f" - {date}" if date else ""), ""]
    buckets = classify(subjects)
    for name in [n for n, _ in SECTIONS] + ["Other"]:
        items = buckets[name]
        if not items:
            continue
        lines.append(f"### {name}")
        lines += [f"- {i}" for i in items]
        lines.append("")
    return "\n".join(lines)


def build():
    version = (REPO / "VERSION").read_text().strip()
    ts = tags()
    out = [
        "# Changelog",
        "",
        "Generated by `tools/changelog.py` from the commit log. Every entry is a",
        "real commit; nothing here is written by hand.",
        "",
    ]
    if ts:
        newest = ts[0]
        pending = commits(f"{newest}..HEAD")
        if pending:
            out.append(render_release("Unreleased", "", pending))
        for i, t in enumerate(ts):
            prev = ts[i + 1] if i + 1 < len(ts) else None
            rng = f"{prev}..{t}" if prev else t
            date = git("log", "-1", "--format=%ad", "--date=short", t)
            out.append(render_release(t, date, commits(rng)))
    else:
        out.append(render_release(f"v{version}", git("log", "-1", "--format=%ad", "--date=short"),
                                  commits("HEAD")))
    return "\n".join(out).rstrip() + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        if OUT.is_file() and OUT.read_text() == text:
            print("ok  CHANGELOG.md is current")
            return 0
        print("CHANGELOG.md is behind. Run: python3 tools/changelog.py", file=sys.stderr)
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.name} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
