#!/usr/bin/env python3
"""Which of the 1000 items are actually fixed, read from the commit log.

A claim about progress that nobody can check is worth nothing. Every commit
that closes an item says so in its message ("Fixes items 12, 15, 221-232"), and
this reads those, cross-references docs/1000.md, and writes a status file.

  python3 tools/fixed.py            rewrite docs/1000-STATUS.md
  python3 tools/fixed.py --count    just the number
  python3 tools/fixed.py --open N   show N open items, lowest number first
"""

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LIST = REPO / "docs/1000.md"
OUT = REPO / "docs/1000-STATUS.md"
# Tolerant on purpose: the claim wraps across lines, and a commit may say
# "169 (partly)". The first version required the whole thing on one line and
# silently missed a third of the commits, which is exactly the kind of quiet
# undercount this file exists to prevent.
CLAIM = re.compile(r"Fixes items?\s+(.+?)\s+of\s+docs/1000\.md", re.I | re.S)
# An item that was wrong when written is closed too, and counted separately.
# Rolling corrections into "fixed" would inflate the number with entries that
# never needed work.
CORRECT = re.compile(r"Corrects items?\s+(.+?)\s+of\s+docs/1000\.md", re.I | re.S)
NUMS = re.compile(r"(\d+)\s*-\s*(\d+)|(\d+)")


def items():
    """Every numbered line in the list, as {number: text}."""
    out = {}
    section = None
    for line in LIST.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^## \d+\. (.+)$", line)
        if m:
            section = m.group(1)
            continue
        m = re.match(r"^(\d+)\.\s+(.*)$", line)
        if m:
            out[int(m.group(1))] = (section or "?", m.group(2))
    return out


def claimed():
    """Item numbers closed by commits, mapped to the commit that closed them."""
    log = subprocess.run(
        ["git", "-C", str(REPO), "log", "--pretty=%H%x00%s%x00%b%x1e"],
        capture_output=True, text=True,
    ).stdout
    fixed, corrected = {}, {}
    for entry in log.split("\x1e"):
        if not entry.strip():
            continue
        sha, subject, body = (entry.strip().split("\x00") + ["", ""])[:3]
        for pattern, bucket in ((CLAIM, fixed), (CORRECT, corrected)):
            for m in pattern.finditer(body):
                for lo, hi, one in NUMS.findall(m.group(1)):
                    if one:
                        bucket.setdefault(int(one), (sha[:7], subject))
                    else:
                        for n in range(int(lo), int(hi) + 1):
                            bucket.setdefault(n, (sha[:7], subject))
    return fixed, corrected


def main():
    all_items = items()
    fixed_all, corrected_all = claimed()
    done = {n: v for n, v in fixed_all.items() if n in all_items}
    corrected = {n: v for n, v in corrected_all.items() if n in all_items}
    total = len(all_items)

    if "--count" in sys.argv:
        print(f"{len(done)} of {total} fixed ({len(done) / total * 100:.1f}%), "
              f"{len(corrected)} were wrong when written")
        return 0
    if "--open" in sys.argv:
        n = int(sys.argv[sys.argv.index("--open") + 1]) if len(sys.argv) > sys.argv.index("--open") + 1 else 20
        for i in sorted(set(all_items) - set(done) - set(corrected))[:n]:
            sect, text = all_items[i]
            print(f"  {i:>4}  [{sect}] {text[:96]}")
        return 0

    by_section = {}
    for i, (sect, text) in all_items.items():
        by_section.setdefault(sect, []).append(i)

    lines = [
        "# 1000 things: status",
        "",
        f"**{len(done)} of {total} fixed**, and {len(corrected)} were wrong when written.",
        "Generated by `tools/fixed.py` from the commit",
        "log, not written by hand. A commit closes an item by naming it in its message,",
        "so every line below points at the commit that has to justify it.",
        "",
        "Open items are not a backlog anyone promised to finish. Many are deliberate",
        "(see [ROADMAP.md](ROADMAP.md)), and the last category is unreasonable on purpose.",
        "",
        "| Section | Fixed | Was wrong | Total |",
        "| --- | --- | --- | --- |",
    ]
    for sect, nums in by_section.items():
        f = len([n for n in nums if n in done])
        c = len([n for n in nums if n in corrected])
        lines.append(f"| {sect} | {f} | {c} | {len(nums)} |")
    if corrected:
        lines += ["", "## Wrong when written", "",
                  "Entries the list got wrong. See the Corrections section of "
                  "[1000.md](1000.md).", ""]
        for i in sorted(corrected):
            sha, subject = corrected[i]
            sect, text = all_items[i]
            lines.append(f"- **{i}.** {text}  \n  `{sha}` {subject}")
    lines += ["", "## Fixed", ""]
    for i in sorted(done):
        sha, subject = done[i]
        sect, text = all_items[i]
        lines.append(f"- **{i}.** {text}  \n  `{sha}` {subject}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(done)} of {total} fixed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
